title: Porium Blockchain
description: >-
  Blockchain is a digital technology that combines cryptographic, data
  management, networking, and incentive mechanisms between network participants.
  This course is for those interested to learn about the technicality,
  governance and practical applications.
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
